name: Flutter CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-analysis-and-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"  # Use the latest stable Flutter version (supports Dart 3.6.1)

      - name: Verify Dart version
        run: dart --version  # Ensure Dart 3.6.1 is installed

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

  android:
    name: Android CI/CD
    needs: code-analysis-and-testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6"  # Ensure Flutter is installed for this job too

      - name: Verify Dart version
        run: dart --version  # Ensure Dart 3.6.1 is installed

      - name: Build AAB
        run: |
          flutter build appbundle --release
          echo "Removing signing files for extra security"
          rm android/key.*
