name: Flutter CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-analysis-and-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }}

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

  android:
    name: Android CI/CD
    needs: code-analysis-and-testing  # 👈 Ensures android starts after code-analysis-and-testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build AAB
        run: |
          flutter build appbundle --release
          echo "Removing signing files for extra security"
          rm android/key.*
