name: Flutter CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-analysis-and-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"  # Set the desired Flutter version

      - name: Verify Flutter installation
        run: flutter doctor  # Checks if Flutter is installed correctly

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

  android:
    name: Android CI/CD
    needs: code-analysis-and-testing
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"  # Ensure Flutter is installed for this job too

      - name: Verify Flutter installation
        run: flutter doctor  # Checks if Flutter is installed correctly

      - name: Build AAB
        run: |
          flutter build appbundle --release
          echo "Removing signing files for extra security"
          rm android/key.*
